/**
 * Category Seed Script
 * ---------------------
 * Reads categories.csv (from the frontend folder, or copy it next to this file),
 * then inserts MAIN → SUB → SUB_SUB in order so parent ObjectIds resolve correctly.
 * Slug is auto-generated by the Mongoose pre-save hook.
 *
 * Run from the server root:
 *   npx ts-node src/app/modules/category/seed.ts
 */

import mongoose from "mongoose";
import path from "path";
import fs from "fs";
import { Category } from "./category.model";
import { CategoryType } from "./category.interface";
import dotenv from "dotenv";

dotenv.config();

// ── Parse a minimal CSV (handles quoted fields) ───────────────────────────────
function parseCSV(filePath: string): Record<string, string>[] {
  const raw = fs.readFileSync(filePath, "utf-8");
  const lines = raw.trim().split(/\r?\n/);
  const headers = lines[0].split(",").map((h) => h.trim());

  return lines.slice(1).map((line) => {
    const values: string[] = [];
    let cur = "";
    let inQuotes = false;
    for (const ch of line) {
      if (ch === '"') { inQuotes = !inQuotes; continue; }
      if (ch === "," && !inQuotes) { values.push(cur.trim()); cur = ""; continue; }
      cur += ch;
    }
    values.push(cur.trim());

    return headers.reduce<Record<string, string>>((acc, h, i) => {
      acc[h] = values[i] ?? "";
      return acc;
    }, {});
  });
}

// ── Main ──────────────────────────────────────────────────────────────────────
async function seed() {
  const DB_URL = process.env.DB_URL;
  if (!DB_URL) throw new Error("DB_URL is not set in .env");

  console.log("🔌 Connecting to MongoDB...");
  await mongoose.connect(DB_URL);
  console.log("✅ Connected\n");

  // Path to the CSV — adjust if you moved it
  const csvPath = path.resolve(
    __dirname,
    "../../../../..",          // goes up to mission-bazar root
    "mission-bazar-frontend",
    "categories.csv"
  );

  if (!fs.existsSync(csvPath)) {
    throw new Error(`CSV not found at: ${csvPath}\nCopy categories.csv next to this seed.ts file and update the path.`);
  }

  const rows = parseCSV(csvPath);
  console.log(`📄 Loaded ${rows.length} rows from CSV\n`);

  // Keep a name → _id map so children can look up their parent
  const nameToId = new Map<string, mongoose.Types.ObjectId>();

  // ── Helper: insert one level ───────────────────────────────────────────────
  async function insertLevel(type: CategoryType) {
    const level = rows.filter((r) => r.type === type);
    console.log(`➡  Inserting ${level.length} ${type} categories…`);
    let created = 0;
    let skipped = 0;

    for (const row of level) {
      const parentId = row.parent_name ? nameToId.get(row.parent_name) : undefined;

      if (type !== CategoryType.MAIN && !parentId) {
        console.warn(`  ⚠  Skipping "${row.name}" — parent "${row.parent_name}" not found`);
        skipped++;
        continue;
      }

      // Check for duplicates (same name + same parent)
      const existing = await Category.findOne({
        name: { $regex: new RegExp(`^${row.name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, "i") },
        parent: parentId ?? null,
      });

      if (existing) {
        console.log(`  ⏭  Already exists: "${row.name}" — storing its _id`);
        nameToId.set(row.name, existing._id as mongoose.Types.ObjectId);
        skipped++;
        continue;
      }

      const doc = await Category.create({
        name:     row.name,
        type,
        parent:   parentId ?? null,
        isActive: row.isActive !== "false",
        order:    Number(row.order) || 0,
      });

      nameToId.set(row.name, doc._id as mongoose.Types.ObjectId);
      console.log(`  ✔  "${doc.name}" → slug: "${doc.slug}" (_id: ${doc._id})`);
      created++;
    }

    console.log(`   Done: ${created} created, ${skipped} skipped\n`);
  }

  // ── Insert in order ───────────────────────────────────────────────────────
  await insertLevel(CategoryType.MAIN);
  await insertLevel(CategoryType.SUB);
  await insertLevel(CategoryType.SUB_SUB);

  console.log("🎉 Seed complete!");
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error("❌ Seed failed:", err.message);
  process.exit(1);
});
